sonar.organization=jeronimozapata
sonar.projectKey=JeronimoZapata_parcial2-zapata
sonar.projectName=parcial2-zapata

sonar.sources=src
sonar.tests=test

sonar.exclusions=dist/**,node_modules/**,coverage/**
sonar.test.inclusions=test/**/*.test.ts